version: "3.4"

services:
  webapp:
    environment:
    - NGINX_HOST=0.0.0.0
    - NGINX_PORT=80
    image: nginx:1
    ports:
    - 8080:80
    volumes:
    - ./.nginx:/etc/nginx/nginx.conf
    - ./dist:/app
